# Generated by Django 3.2.11 on 2022-02-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textAnnotation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='banned',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotations',
            name='custom_p',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AddField(
            model_name='annotations',
            name='gender',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotations',
            name='hate_speech',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotations',
            name='offensive',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotations',
            name='other',
            field=models.CharField(default='default_val', max_length=100),
        ),
        migrations.AddField(
            model_name='annotations',
            name='p1',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AddField(
            model_name='annotations',
            name='p2',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AddField(
            model_name='annotations',
            name='p3',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AddField(
            model_name='annotations',
            name='p4',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AddField(
            model_name='annotations',
            name='p5',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AddField(
            model_name='annotations',
            name='parent_text',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AddField(
            model_name='annotations',
            name='race',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotations',
            name='religion',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='annotations',
            name='selection',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='annotations',
            name='submission_text',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AddField(
            model_name='annotations',
            name='subreddit',
            field=models.CharField(default='default_val', max_length=100),
        ),
        migrations.AddField(
            model_name='annotations',
            name='subrules',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AddField(
            model_name='annotations',
            name='text',
            field=models.CharField(default='default_val', max_length=2000),
        ),
        migrations.AlterField(
            model_name='annotations',
            name='u_id',
            field=models.CharField(default='default_val', max_length=100),
        ),
    ]
