# Generated by Django 3.2.11 on 2022-02-08 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textAnnotation', '0002_auto_20220208_0604'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='annotated',
            field=models.BooleanField(default=False),
        ),
    ]
