# Generated by Django 3.2.11 on 2022-02-08 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textAnnotation', '0004_annotations_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subreddit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default_val', max_length=100)),
                ('subrules', models.CharField(default='default_val', max_length=3000)),
            ],
        ),
        migrations.AlterField(
            model_name='annotations',
            name='subrules',
            field=models.CharField(default='default_val', max_length=3000),
        ),
    ]
