# Generated by Django 3.2.11 on 2022-02-08 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textAnnotation', '0005_auto_20220208_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='redrules',
            field=models.CharField(default='default_val', max_length=2000),
        ),
    ]
