# Generated by Django 3.2.11 on 2022-02-08 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textAnnotation', '0006_annotations_redrules'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='orientation',
            field=models.IntegerField(default=0),
        ),
    ]
