# Generated by Django 3.2.11 on 2022-02-08 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textAnnotation', '0007_annotations_orientation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotations',
            name='selection',
            field=models.CharField(default='default_val', max_length=10000),
        ),
    ]
