# Generated by Django 3.2.11 on 2022-02-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textAnnotation', '0009_annotations_context_helpful'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='skip',
            field=models.BooleanField(default=False),
        ),
    ]
