# Generated by Django 3.2.11 on 2022-02-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textAnnotation', '0010_annotations_skip'),
    ]

    operations = [
        migrations.AddField(
            model_name='annotations',
            name='permalink',
            field=models.CharField(default='default_val', max_length=100),
        ),
    ]
